In [ ]:
# Question 1
import numpy as np # a ecrire une fois seulement
tableau = np.array([[10,20,15],[30,40,50]])
print(tableau)
liste = tableau.tolist() # transformer le tableau en liste
print(liste)
print(type(liste)) # pour le type de variable
Taille=tableau.shape # pour les dimensions de la matrice
print(Taille)
New_shape= tableau.reshape(6,1) # pour changer les dimensions, les nouvelles dimensions doivent diviser le nbr total d'elements 
print(New_shape)

[[10 20 15]
 [30 40 50]]
[[10, 20, 15], [30, 40, 50]]
<class 'list'>
(2, 3)
[[10]
 [20]
 [15]
 [30]
 [40]
 [50]]


In [ ]:
#Question2 
#Méthode 1 avec np.tarce()
matrice1= np.array([[6,12,18],[9,3,27],[18,5,1]])
print(matrice1)
trace = np.trace(matrice1)
print(trace)

[[ 6 12 18]
 [ 9  3 27]
 [18  5  1]]
10


In [ ]:
#Méthode 2

In [ ]:
#Question 3
matrice2= np.array([[11,9,32],[100,22,78],[4,15,90]])
print(matrice2)
print(matrice2[matrice2>50])

[[ 11   9  32]
 [100  22  78]
 [  4  15  90]]
[100  78  90]


In [ ]:
#Question4
A = np.array([[3,13,30],[4,14,44],[5,15,55]])
B = np.array([[2,12,22],[1,11,11],[6,1,66]])
C= A+B
print(C)

[[  5  25  52]
 [  5  25  55]
 [ 11  16 121]]


In [ ]:
#Question5
D=np.mean(C)
print(D) # la moyenne de toute la matrice
E=np.mean(C, axis=1) # donne la moyenne des lignes
F=np.mean(C, axis=0) # donne la moyenne des colonnes 
print(E)
print(F)
G = C - F # on soustrait de chaque element la moyenne de sa colonne 
print(G)

# on utilise np car c'es noté touuut en haut, si j'avais mis numpy en haut fallait mettre .numpy

35.0
[27.33333333 28.33333333 49.33333333]
[ 7. 22. 76.]
[[ -2.   3. -24.]
 [ -2.   3. -21.]
 [  4.  -6.  45.]]


In [ ]:
import numpy as np
a=np.array([[11,22,33,44],[10,20,30,40],[38,65,79,42]]) #ne pas oublier de doubler les crochets sur les extrémités 
print(a)
print("espace")
print(a[0,:]) # afficher la premier ligne seulement
print("espace")
print(a[1,2]) #pour afficher un element de la matrice, dans ce cas ligne ligne 1"second" colonne 2"third"

[[11 22 33 44]
 [10 20 30 40]
 [38 65 79 42]]
espace
[11 22 33 44]
espace
30


In [ ]:
import pandas as pd
color=["pink", "white", "black", "blue"]
occurence = [20, 15, 6, 43]
S=pd.Series(occurence, index=color) #on choisit l'index, couleur dans ce cas 
print(S)

pink     20
white    15
black     6
blue     43
dtype: int64


In [ ]:
dictionary  = { 'name' : ['Jack', 'Thomas', 'Alexandre'],
    'age' : [34, 30, 16],
    'city' : ['Paris', 'Roma', 'New York']}

df = pd.DataFrame(dictionary)
print(df)

        name  age      city
0       Jack   34     Paris
1     Thomas   30      Roma
2  Alexandre   16  New York
